length check
changhyun-cra/SimiliarityChecker-0419 pull request #1
Opened 2024-07-03 23:37 UTC by changhyun-cra

2024-07-04 00:22 UTC, jh-cra requested changes
B 길이가 길 때의 test case 추가 하면 좋겠습니다

2024-07-04 00:44 UTC, changhyun-cra commented
> B 길이가 길 때의 test case 추가 하면 좋겠습니다

말씀해주신 Test Case 추가했습니다.
의견 감사합니다~!

2024-07-04 01:01 UTC, jh-cra requested changes
Test case  에서 B 가 A 보다 2배 더 큰 경우가 있으면 좋겠습니다.

2024-07-04 01:07 UTC, changhyun-cra commented
> Test case 에서 B 가 A 보다 2배 더 큰 경우가 있으면 좋겠습니다.
말씀해주신 Test Case 추가했습니다.
의견 감사합니다~!

2024-07-05 12:42 UTC, bootplus-hub approved these changes

2024-07-07 23:13 UTC, bootplus-hub approved these changes

2024-07-07 23:13 UTC, merged